#theme: jekyll-theme-minimal

theme: minima

plugins:
  - jekyll-feed
  - jekyll-seo-tag
  
title: Page d'accueil de mon porfolio
description: Ajoutez ceci à vos favoris pour garder un œil sur les mises à jour de mon projet !
